drop table if exists member;

create table member(
    id bigint generated by default as identity, 
    name varchar(255),
    primary key (id)
);


insert into member(name) values ('kkk1');
insert into member(name) values ('mmm1');
insert into member(name) values ('sss1');