--DROP TABLE IF EXISTS ARTICLE;
--DROP TABLE IF EXISTS COMMENT;
--DROP TABLE IF EXISTS ARTICLE_TYPE;


CREATE TABLE IF NOT EXISTS ARTICLE (
    ID VARCHAR(50), 
    TITLE VARCHAR(500),
    CONTENT TEXT(50000),
    ARTICLE_TYPE VARCHAR(5),
    DELETE_FLG VARCHAR(1),
    CRE_ID VARCHAR(50), 
    CRE_DT DATE, 
    UPD_ID VARCHAR(50),
    UPD_DT DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMMENT(
    ID VARCHAR(50), 
    ARTICLE_ID VARCHAR(50),
    TITLE VARCHAR(500),
    CONTENT TEXT(10000), 
    DELETE_FLG VARCHAR(1),
    CRE_ID VARCHAR(50), 
    CRE_DT DATE, 
    UPD_ID VARCHAR(50),
    UPD_DT DATE
);


CREATE TABLE IF NOT EXISTS ARTICLE_TYPE(
    ID VARCHAR(10),
    TYPE_CD VARCHAR(5),
    DESCRIPTION VARCHAR(600), 
    PRIMARY KEY (ID)
);



/*
    Generate Init Data 
*/
INSERT IGNORE INTO ARTICLE_TYPE(ID, TYPE_CD, DESCRIPTION) VALUES ('1', 'N', 'normal article');
INSERT IGNORE INTO ARTICLE_TYPE(ID, TYPE_CD, DESCRIPTION) VALUES ('2', 'C', 'comment');